### ISSUE TITLE
(JUG) 你要是愿意这么用Scope的话，我也没什么好说的了

### ISSUE THREAD

**Issue by chuigda** [ckx-lang/ckxc-v2-proto#4]
所以你到底想怎么管理scope的问题：某些函数需要scope来指定将声明插入到哪里，而某些则不需要。更关键的是，对其他信息和DeclContext的处理基本上已经分开了，我们需要再把scope分出去么？创建三套函数？

**Comment by chuigda** [comment]
(JUG) 简而言之当前函数的组织极其混乱，你需要重新组织它们

**Comment by chuigda** [comment]
(TOP) 总的来说把scope和declContext分开，让sema来决定何时addToContext，这点是没问题的。但是现在的函数组织使程序的语义不够清晰。很关键的一点是，组织函数的时候不应该以“尽可能显式(比如把一定要把ActOnVar和ActOnField/Global分开)”为准，而是以“顺应其自然的含义”为标准。

**Comment by chuigda** [comment]
(MID) 我打算把函数拆成两部分，actOnVar/Class/Enum基于声明的类型来做一些事情；actOnLocal/Global/Field基于声明的上下文来做一些事情

还有JUG，你要是愿意这样使用issues的话，我也没什么好说的了

**Comment by chuigda** [comment]
(JUG) 很好，但是ActOnEnumerator这类函数怎么办？还是要分成两部分咯？

**Comment by chuigda** [comment]
(TOP) 没必要追求完全的一致吧

**Comment by chuigda** [comment]
(JUG) MID你死了吗

**Comment by chuigda** [comment]
(MID) 最后决定分成三部分
```
ActOnXXXDecl
ActOnDeclInScope
ActOnDeclInContext

```
中央里已经决定了，这种东西必须explicit起来。

**Comment by chuigda** [comment]
(ADC) 已在本提交 https://github.com/ckx-lang/ckxc-v2-proto/commit/e7c997cf4d3fc2bfb00d7cfb1827aab7532edc05 完成修改。注意actOnEnumerator暂时没有修改，我跟MID对这个问题还有争议

**Comment by ice1000** [comment]
(ICE) 更推荐在commit里mention一个issue
