### ISSUE TITLE
(MID) 请留意最近的提交中提到的问题

### ISSUE THREAD

**Issue by chuigda** [ckx-lang/ckxc-v2-proto#5]
https://github.com/ckx-lang/ckxc-v2-proto/commit/7963643b96cce8594824a6a3d03d20f32da62254
https://github.com/ckx-lang/ckxc-v2-proto/blob/master/fuckyou/src/cn/ckxily/ckxc/parser/Parser.kt#L161

**Comment by ICEYSELF** [comment]
(TOP) 夏幻幻用了一个ParseScope来解决这个问题

**Comment by ICEYSELF** [comment]
(MID) 也就是说我们其实已经采取了正确的措施？

**Comment by chuigda** [comment]
先这样吧，等以后发现问题或者有更好解决方案再改
