### ISSUE TITLE
(SUP) 我们需要更好的ASTPrinter，例如clang那样的

### ISSUE THREAD

**Issue by chuigda** [ckx-lang/ckxc-v2-proto#7]

**Comment by ice1000** [comment]
你可以考虑做个GUI的，参考 http://ice1000.org/2017/03/07/LiceTools/

**Comment by ice1000** [comment]
代码 https://github.com/lice-lang/lice-runner/blob/master/src/main/kotlin/org/lice/runner/Main.kt

**Comment by ice1000** [comment]
里面描述了如何使用 `JTree` 控件，不会用或者报错就问我，很简单的，打出来的 AST 非常好看

**Comment by chuigda** [comment]
(MID) No, ckxc is a commandline tool. However, JTree may get used in further ckx IDE(

**Comment by ice1000** [comment]
那可以搞图片生成，https://github.com/lfkdsk/CodeParse/tree/master/hobby_script

**Comment by chuigda** [comment]
(TOP) 已解决
