### ISSUE TITLE
(JUG) MID, TOP和ADC你们三个都写了些什么垃圾

### ISSUE THREAD

**Issue by chuigda** [ckx-lang/ckxc-v2-proto#8]
我知道我们是在做快速原型，但是为了做快速原型就可以糊屎是吗？你们怎么这么垃圾？
就以下面的代码为例，ckxc竟然拒不接受这样的代码，而且报错的还不是ckxc，而是JVM！？
```
    let mut vi32 a = 8;
    let mut vi32& b = a;
```
你们竟然对引用类型毫无处理，甚至在Implicit Cast中强制要求BuiltinType，接口里却什么都不写？接受什么类型这不是应该写进接口的吗，我可去你妈的as和assert吧！

**Comment by chuigda** [comment]
(JUG) 不是我说你们，有空好好去看看ckxc第一版的代码，你们现在的代码水平简直令人发指。

**Comment by chuigda** [comment]
(MID) JUG你是傻叉吗，第一版哪有reference什么事

**Comment by chuigda** [comment]
(MID) 已在最近若干次提交中修复问题

**Comment by ice1000** [comment]
我觉得应该把你的小号都封了。
这是为了你好，免得你精神分裂。
